### ISSUE TITLE
Fuels  :- items are not showing on detail page 

### ISSUE THREAD

**Issue by rashmi0301** [Fleet-Hawks-Inc/fh-cloud-app#982]
1. description is not showing 
2. odometer should be appear miles not mi
3. fuel stop details are not showing except vendor 
4. payment details under the paid by , payment mode , fuel card number , reimburse to drive r, deduct to pay -- these options are not showing 
5. price/gallon -- wrong data is showing 
6. DEF fuel quantity -- units are not showing 
7. discount type , tax type and prices are not showing 
8. subtotal quantity is not showing

**Comment by rashmi0301** [comment]
NOT DONE 

1.DEF Fuel Quantity -- unit is not showing --- detail page 
2. discount type and discount CAD is not showing properly -- detail page
3.  Taxes -- should have space if we are having more than one taxes --detail page
4. cost per liter that i had added this is not showing on -- detail / list page 
5. payment details under the paid by , payment mode , fuel card number , reimburse to driver, deduct to pay -- these options are not showing -- DETAIL PAGE
6. description is not showing
7. odometer should be appear miles not mi

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116055868-caa64200-a69a-11eb-918b-eb64d923a99c.png)

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/116057034-07bf0400-a69c-11eb-9021-58e6a8a2079a.png)

**Comment by rashmi0301** [comment]
when we are on editing page then values are changed .. these are not showing that i had earlier while adding fuel entry

**Comment by rashmi0301** [comment]
1. description is not showing -- DONE 
2. odometer should be appear miles not mi -- DONE 
3. fuel stop details are not showing except vendor  -- DONE 
4. payment details under the paid by , payment mode ,reimburse to drive r, deduct to pay -- these options are not showing -- DONE 
5. price/gallon -- wrong data is showing -- DONE  ( after adding values are changed on detail page as well as editing page )
6. DEF fuel quantity -- units are not showing  -- DONE 
7.  tax type and prices are not showing -- DONE 
8. subtotal quantity is not showing -- DONE 
9. Broken image -- DONE

**Comment by rashmi0301** [comment]
NOT DONE :- 

1. Discount is not showing properly 
2. fuel card field is missing on detail page 
3. reimburse , deduct to pay should be appear on different field 
4. I had added gallon unit but on detail/ editing page litre is showing . please discuss regarding this and as well as values .
5.  fuel integration -- PENDING 
6. please fix the dropdown overlap issues for all fields

**Comment by Hardeep8587** [comment]
@rashmi0301 please check above points on devapp

**Comment by rashmi0301** [comment]
on detail page 

vehicle fuel quantity is missing 
discount type name is not there 
total gallon where it is coming from ?

**Comment by Hardeep8587** [comment]
![Uploading image.png…]()

**Comment by rashmi0301** [comment]
discount type name is not there -- pending
now 

city is not showing 
date format 00 should not appear -- list , detail page

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/118655033-01eda780-b79e-11eb-9b49-ccef7c005252.png)

if i entered another payment mode then still fuel card is showing

**Comment by Hardeep8587** [comment]
@rashmi0301 this is done, I fixed front end validation I will push code tomorrrow

**Comment by rashmi0301** [comment]
@Hardeep8587 

now on list view page -- m not getting the vendor , fuel amount , fuel unit data 
detail page - m not getting the discount still . and if m not entered any data in discount field then discount field is not showing as well . and when i filled the discount field then discount name is not showing

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119051466-0cfc2f80-b978-11eb-8c52-6a17ebbff662.png)

00 is showing

**Comment by rashmi0301** [comment]
![image](https://user-images.githubusercontent.com/79301742/119051842-8e53c200-b978-11eb-853d-22215f37ecd9.png)

in some of the state i m not getting the city data

**Comment by rashmi0301** [comment]
checked fuel on live ( sixteen.may login ) 

issues :- 

1. Still not showing the vendor on list page 
2. units are not showing with the DEF fuel quantity -- detail page 
3. still city is not showing
4. Description , attach photo , select trip -- not appear in detail page

**Comment by rashmi0301** [comment]
checked fuel on ( rashmifleethawks login) 

1. list view :- province is not showing . Only country ad city is showing 
2. vendor data is not showing -- list page 
3. fuel units -- units are not showing -- list page 
rest issues are same as per the live issue

**Comment by rashmi0301** [comment]
DONE
